#!/usr/bin/env sage -python

from sage.all import *

G = PermutationGroup(["(1,2,3,4)","(1,3)(5,6,7,8)"])
print("Group elements: \n{}".format(G.list()))
sigma = G("(1,2,3,4)")
H = G.subgroup([sigma])
print("Subgroup generated by <a>: \n{}".format(H.list()))
print("Right Cosets: \n{}".format(G.cosets(H, side='right')))
print("Left Cosets: \n{}".format(G.cosets(H, side='left')))
